// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpEy2COaK9oRE5F2UxAuCgsWkdEsjtcAc',
    appId: '1:1085403637707:web:9f652fc68504eee333f84e',
    messagingSenderId: '1085403637707',
    projectId: 'sayyad-1f8e6',
    authDomain: 'sayyad-1f8e6.firebaseapp.com',
    storageBucket: 'sayyad-1f8e6.firebasestorage.app',
    measurementId: 'G-FJ07HD962R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD96Ek-OlR6U1A8Tq2s-V_aZYTinYJhOTw',
    appId: '1:1085403637707:android:978157c31f0cd58f33f84e',
    messagingSenderId: '1085403637707',
    projectId: 'sayyad-1f8e6',
    storageBucket: 'sayyad-1f8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWgSZGoqt4BGFBLkKcQ30UhnvqlFS_cTc',
    appId: '1:1085403637707:ios:6c8faf8b9114a96533f84e',
    messagingSenderId: '1085403637707',
    projectId: 'sayyad-1f8e6',
    storageBucket: 'sayyad-1f8e6.firebasestorage.app',
    iosBundleId: 'com.example.sayyad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWgSZGoqt4BGFBLkKcQ30UhnvqlFS_cTc',
    appId: '1:1085403637707:ios:6c8faf8b9114a96533f84e',
    messagingSenderId: '1085403637707',
    projectId: 'sayyad-1f8e6',
    storageBucket: 'sayyad-1f8e6.firebasestorage.app',
    iosBundleId: 'com.example.sayyad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpEy2COaK9oRE5F2UxAuCgsWkdEsjtcAc',
    appId: '1:1085403637707:web:c8c7b1dabdc7895633f84e',
    messagingSenderId: '1085403637707',
    projectId: 'sayyad-1f8e6',
    authDomain: 'sayyad-1f8e6.firebaseapp.com',
    storageBucket: 'sayyad-1f8e6.firebasestorage.app',
    measurementId: 'G-LTLCM8QD2T',
  );
}
